"""Idempotent reference data, safe to run on every startup (any environment).

Lives in `shared/` for the same reason `shared/models.py` does: the only table
it seeds is authorization infrastructure, owned by no domain and generated by
no DSL entity — a `{domain}/seeds.py` would either be clobbered by the
generator's next run or imply a business owner that does not exist.

`main.py`'s lifespan calls `seed_default_reference` at boot, so the operator's
e-mail is on the allowlist with no manual step, in dev, tests and production
alike. `ON CONFLICT DO NOTHING` makes the insert a no-op once the row exists.
"""

from __future__ import annotations

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

# The operator's own e-mail: without it the very first login of a fresh
# deployment would be refused with `not_allowlisted` and there would be no
# authorized identity left to grant access with.
DEFAULT_ALLOWED_EMAILS = ["henricos@gmail.com"]


async def seed_default_reference(engine: AsyncEngine) -> None:
    """Insert the default allowlist entries, normalized, skipping duplicates.

    Raw `text()` instead of the ORM on purpose: a seed must not depend on the
    mapped classes staying shaped the way they are today, and the statement is
    the same one both operator scripts run.
    """
    async with engine.begin() as connection:
        for email in DEFAULT_ALLOWED_EMAILS:
            await connection.execute(
                text(
                    "INSERT INTO allowed_emails (email) VALUES (:email) "
                    "ON CONFLICT (email) DO NOTHING"
                ),
                {"email": email.strip().lower()},
            )
